import time

while True:

    # ask for usr input
    print("Input 1 to generate new image")
    print("Input 2 to exit")
    option = input()
    
    if option == "1":
        # write "run" to prng-service.txt
        with open('prng-service.txt', 'w', encoding="utf-8") as f:
            f.write("run\n")
        f.closed

        time.sleep(5.0)
        
        # read the random number generated by Prng.py
        with open('prng-service.txt', 'r', encoding="utf-8") as f:
            line = f.readline()
        f.closed

        num = int(line)
        # write the random number to image-service.txt
        with open('image-service.txt', 'w', encoding="utf-8") as f:
            f.write(f"{num}\n")
        f.closed

        time.sleep(5.0)
        # find the path of the image
        with open('image-service.txt', 'r', encoding="utf-8") as f:
            line = f.readline()
        f.closed

        print(line)

    elif option == "1":
        break


